name: plantica
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+1
  http: ^1.1.0

  connectivity_plus: ^4.0.0
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_slidable: ^3.1.1
  google_fonts: ^6.2.1
  sqflite: 2.2.8+4
  shared_preferences: ^2.0.15
  path: ^1.8.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/

