name: plantica
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^4.0.0
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_slidable: ^3.1.1
  sqflite: 2.2.8+4
  shared_preferences: ^2.0.15
  flutter_blue: ^0.8.0
  crypto: ^3.0.0
  http: ^1.0.0
  google_fonts: ^6.2.1
  uuid: ^3.0.6 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/

